---

- name: Playbook to install kubevirt
  hosts: kubeflow_hosts
  collections:
    - kcd.k8s
  tasks:
    - name: ROLE Install K8s with kubeadm
      ansible.builtin.import_role:
        name: install
    - name: ROLE Configure ingress and dashboard
      ansible.builtin.import_role:
        name: config-ingress