#SPDX-License-Identifier: MIT-0
---

- name: Add sope user
  ansible.builtin.user:
    name: sope
    group: users
    state: present
    shell: /bin/bash
    createhome: true

- name: Ensure /home/sope/.ssh directory exists
  ansible.builtin.file:
    path: /home/sope/.ssh
    state: directory
    mode: '0700'
    owner: sope
    group: users

- name: Set ssh key
  ansible.builtin.copy:
    content: "{{ lookup('file', 'id_ed25519.pub') }}"
    dest: /home/sope/.ssh/authorized_keys
    owner: sope
    group: users
    mode: '0600'

## ADD for developer stage and remove for production
- name: Add sope to wheel group
  ansible.builtin.user:
    name: sope
    groups: wheel
    append: true
    state: present

## ADD for developer stage and remove for production
- name: Add sope to sudoers with no password
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^sope ALL=\(ALL\) NOPASSWD:ALL$'
    line: 'sope ALL=(ALL) NOPASSWD:ALL'
    validate: 'visudo -cf %s'
  become: true

- name: Add or modify nofile limit for all users
  community.general.pam_limits:
    domain: "*"
    limit_type: '-'
    limit_item: nofile
    value: 2048
  become: true

- name: Install Linux packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop:
    - python3-pip
    - firewalld
    - net-tools
    - vim
    - git
    - haproxy
    - cockpit
    - cockpit-machines
    - cockpit-storaged

- name: Enable Linux services
  ansible.builtin.systemd:
    name: "{{ item }}"
    enabled: true
    masked: false
    state: started
  loop:
    - firewalld
    - cockpit
    - haproxy

- name: Install Pip packages
  ansible.builtin.pip:
    name: "{{ item }}"
    state: present
  loop:
    - kubernetes
    - cryptography

- name: Set hostname
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}"

- name: Disable swap mount
  ansible.posix.mount:
    name: "{{ item }}"
    fstype: swap
    state: absent
  loop: ["none", "swap"]

- name: Disable swap command
  ansible.builtin.command:
    cmd: "swapoff -a"
  when: ansible_swaptotal_mb > 0

- name: Disable SELinux
  ansible.posix.selinux:
    policy: targeted
    state: disabled

- name: Add modprobe modules
  community.general.modprobe:
    name: "{{ item }}"
    state: present
  loop: [br_netfilter, overlay]

- name: Configure firewalld
  ansible.posix.firewalld:
    port: "{{ item }}/udp"
    permanent: true
    state: enabled
    immediate: true
    zone: public
  loop: "{{ configure_hosts_k8s_ports }}"

- name: Add rich rule to firewalld
  ansible.posix.firewalld:
    rich_rule: 'rule family="ipv4" source address="10.0.0.0/8" accept'
    permanent: true
    state: enabled
    immediate: true
    zone: public
  become: true

- name: Configure kernel parameters
  ansible.posix.sysctl:
    name: "{{ item }}"
    value: '1'
    sysctl_set: true
    reload: true
  loop:
    - net.bridge.bridge-nf-call-ip6tables
    - net.bridge.bridge-nf-call-iptables
    - net.ipv4.ip_forward

- name: Configure repos for kubernetes packages
  ansible.builtin.template:
    src: "{{ item }}"
    dest: /etc/yum.repos.d/{{ item | regex_replace('.j2', '') }}
    owner: root
    group: root
    mode: '0644'
  become: true
  loop:
    - kubernetes.repo.j2
    - cri-io.repo.j2

- name: Install Kubernetes packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop:
    - cri-o
    - kubelet
    - kubeadm
    - kubectl

- name: Enable Kubernetes services
  ansible.builtin.systemd:
    name: "{{ item }}"
    enabled: true
    masked: false
    state: started
  loop:
    - kubelet
    - crio
